### PR TITLE
Update to embedded-hal-1.0.0

### PR DESCRIPTION
**Pull request by irii**
Hi! Thank you for helping out with SSD1306 development! Please:

- [x] Check that you've added documentation to any new methods
- [x] Rebase from `master` if you're not already up to date
- [x] Add or modify an example if there are changes to the public API
- [x] Add a `CHANGELOG.md` entry in the **Unreleased** section under the appropriate heading (**Added**, **Fixed**, **Changed**, etc)
- [x] Run `rustfmt` on the project with `cargo fmt --all` - CI will not pass without this step
- [ ] Check that your branch is up to date with master and that CI is passing once the PR is opened

## PR description

Updated to embedded-hal 1.0.0
Updated rust-version to 1.75 for display-interface package

- > Works on an CM4 module with I2C

### CODE REVIEW

**Review by jamwaffles — CHANGES_REQUESTED** [review]
Looks good aside from a tweak to the changelog. I appreciate the attention to detail in changing the CI config too - thanks!

**Comment by jamwaffles** [comment]
P.s. CI is failing. I don't have much time to look into it right now so I'd appreciate it if you can see if you can fix the issues.

**Comment by irii** [comment]
Thanks for the information. I will have a look by time. BR

**Comment by irii** [comment]
@Sycrosity Currently not. All examples use the stm32f1xx-hal library. This library currently has no support for embedded hal 1.0 which is the main reason for the currently paused development.

**Comment by Sycrosity** [comment]
> @Sycrosity Currently not. All examples use the stm32f1xx-hal library. This library currently has no support for embedded hal 1.0 which is the main reason for the currently paused development.

If it would help, I would happily switch the examples over to something like `esp-hal`, which I am quite familar with writing code for.

**Comment by ne0h** [comment]
Any progress so far? I would also much appreciate if this PR would be merged as it also solves my issue (https://github.com/jamwaffles/ssd1306/pull/211).

**Comment by irii** [comment]
Currently not.

A workaround would be to use https://github.com/ryankurte/embedded-hal-compat which has now offical support for embedded-hal 1.0.0

BR,
Ivan

**Comment by eldruin** [comment]
Fixed in #213. Thank you for your work!

**Pull request closed without merging**
